name: CD

on:
  pull_request:
    branches: [ release ]

jobs:
  cd:
    name: CD
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Restore debug google-services.json
      run: |
        echo "${{ secrets.GOOGLE_JSON_DEBUG }}" > app/src/debug/google-services.json
    - name: Restore release google-services.json
      run: |
        echo "${{ secrets.GOOGLE_JSON_RELEASE }}" > app/src/release/google-services.json
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
        check-latest: false
        cache: 'gradle'
    - name: Run all unit tests
      run: ./gradlew testDebug --info
    - name: Assemble release APK
      run: ./gradlew assembleRelease --info
    - name: Upload release APK
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: app/build/outputs/apk/release/*.apk